"""Keep paper/sections/*.md and paper/paper_full.md in sync, both directions.

Writing happens in the section files; paper_full.md is the single document to
read end to end and to edit when rewriting in one pass. Either file can be the
one that changed, so this joins or splits on demand instead of picking a winner.

    python scripts/build_paper.py            # sections -> paper_full.md
    python scripts/build_paper.py --split    # paper_full.md -> sections
    python scripts/build_paper.py --status   # what changed since the last sync

Each section is wrapped in markers, which is what makes the split exact:

    <!-- SECTION: 05_results -->
    ...text...
    <!-- END: 05_results -->
"""
from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SECTIONS_DIR = ROOT / "paper" / "sections"
FULL = ROOT / "paper" / "paper_full.md"

TITLE = ("Comparative Analysis of CNN and Vision Transformer Architectures for "
         "Explainable Endometriosis Classification in Laparoscopic Images")

ORDER = [
    ("01_abstract", "Abstract"),
    ("02_introduction", "Introduction"),
    ("03_related_work", "Related Work"),
    ("04_methodology", "Methodology"),
    ("05_results", "Results"),
    ("06_discussion", "Discussion"),
    ("07_limitations", "Limitations and Future Work"),
    ("08_conclusion", "Conclusion"),
]

START = "<!-- SECTION: {} -->"
END = "<!-- END: {} -->"
SPLIT_RE = re.compile(r"<!-- SECTION: ([0-9a-z_]+) -->\n(.*?)\n?<!-- END: \1 -->",
                      re.DOTALL)


def join() -> None:
    SECTIONS_DIR.mkdir(parents=True, exist_ok=True)
    parts = [f"# {TITLE}", "",
             f"<!-- Generated by scripts/build_paper.py on {date.today()}.",
             "     Edit this file freely, then run `python scripts/build_paper.py --split`",
             "     to push your changes back into paper/sections/. -->", ""]
    missing = []
    for key, heading in ORDER:
        path = SECTIONS_DIR / f"{key}.md"
        if not path.exists():
            missing.append(key)
            body = f"*(not written yet)*"
        else:
            body = path.read_text(encoding="utf-8").strip()
        parts += [START.format(key), "", body, "", END.format(key), ""]
    FULL.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    written = len(ORDER) - len(missing)
    print(f"joined {written}/{len(ORDER)} sections -> {FULL.relative_to(ROOT)}")
    if missing:
        print("  still empty:", ", ".join(missing))


def split() -> None:
    if not FULL.exists():
        sys.exit(f"{FULL.relative_to(ROOT)} does not exist yet - run without --split first")
    text = FULL.read_text(encoding="utf-8")
    found = SPLIT_RE.findall(text)
    if not found:
        sys.exit("no <!-- SECTION: ... --> markers found; the file cannot be split safely")
    SECTIONS_DIR.mkdir(parents=True, exist_ok=True)
    changed = []
    for key, body in found:
        body = body.strip() + "\n"
        if body.strip() == "*(not written yet)*":
            continue
        path = SECTIONS_DIR / f"{key}.md"
        if path.exists() and path.read_text(encoding="utf-8") == body:
            continue
        path.write_text(body, encoding="utf-8")
        changed.append(key)
    print(f"split {len(found)} sections; updated: {', '.join(changed) if changed else 'none'}")


def status() -> None:
    if not FULL.exists():
        print("paper_full.md does not exist yet")
        return
    full_mtime = FULL.stat().st_mtime
    newer = [p.name for p in sorted(SECTIONS_DIR.glob("*.md"))
             if p.stat().st_mtime > full_mtime]
    text = FULL.read_text(encoding="utf-8")
    drift = []
    for key, body in SPLIT_RE.findall(text):
        path = SECTIONS_DIR / f"{key}.md"
        if path.exists() and path.read_text(encoding="utf-8").strip() != body.strip():
            drift.append(key)
    words = len(re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL).split())
    print(f"paper_full.md: {words} words")
    print("sections newer than paper_full.md:", ", ".join(newer) if newer else "none")
    print("sections whose text differs:", ", ".join(drift) if drift else "none")
    if drift:
        print("  -> run --split to take paper_full.md's version, "
              "or run without flags to take the sections' version")


if __name__ == "__main__":
    if "--split" in sys.argv:
        split()
    elif "--status" in sys.argv:
        status()
    else:
        join()
